name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: checkroutes
      id: checkroutes
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: checkroutes
        setup-command: ''
        command: test -f routes/web.php
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CHECKROUTES_RESULTS: "${{steps.checkroutes.outputs.result}}"
      with:
        runners: checkroutes
